name: Create virtualenv
on:
  - push
jobs:
  Create-Virtualenv:
    runs-on: ubuntu-20.04
    steps:
      - run: pwd ; ls
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: sudo apt install python3 python3-pip
      - run: pip3 install virtualenv
      - run: virtualenv -p python3 test
      - run: |
          source test/bin/activate
          pip3 install -r requirements.txt
